//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandotronWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandotronWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 到头了  已重新生成 的本地化字符串。
        /// </summary>
        public static string AtTheEnd {
            get {
                return ResourceManager.GetString("AtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文档 (*.txt) | *.txt 的本地化字符串。
        /// </summary>
        public static string FileModeFilter {
            get {
                return ResourceManager.GetString("FileModeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多仅允许1000 个学生 的本地化字符串。
        /// </summary>
        public static string HugeNumber {
            get {
                return ResourceManager.GetString("HugeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件，格式为：一行一个人名。 的本地化字符串。
        /// </summary>
        public static string InvalidFileOperation {
            get {
                return ResourceManager.GetString("InvalidFileOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的学生人数，范围为 [1, 1000] 的本地化字符串。
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效操作 的本地化字符串。
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择图片（可选多个） 的本地化字符串。
        /// </summary>
        public static string InvalidPhotoOperation {
            get {
                return ResourceManager.GetString("InvalidPhotoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 (*.png, *.jpg) | *.txt; *.jpg 的本地化字符串。
        /// </summary>
        public static string PhotoModeFilter {
            get {
                return ResourceManager.GetString("PhotoModeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学生人数 的本地化字符串。
        /// </summary>
        public static string StudentAmount {
            get {
                return ResourceManager.GetString("StudentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人名 的本地化字符串。
        /// </summary>
        public static string StuFileMode {
            get {
                return ResourceManager.GetString("StuFileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学号 的本地化字符串。
        /// </summary>
        public static string StuNumberMode {
            get {
                return ResourceManager.GetString("StuNumberMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string StuPhotoMode {
            get {
                return ResourceManager.GetString("StuPhotoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Randotron 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
